
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ASSIGN ID KEYWORD_ENCRYPT KEYWORD_PUBLIC KEYWORD_SECRET KEYWORD_SEND LPAREN NUMBER RPAREN SEMIstatement : KEYWORD_SECRET ID ASSIGN NUMBER SEMIstatement : ID ASSIGN KEYWORD_ENCRYPT LPAREN ID RPAREN SEMIstatement : KEYWORD_SEND LPAREN ID RPAREN SEMI'
    
_lr_action_items = {'KEYWORD_SECRET':([0,],[2,]),'ID':([0,2,7,12,],[3,5,10,15,]),'KEYWORD_SEND':([0,],[4,]),'$end':([1,14,16,18,],[0,-1,-3,-2,]),'ASSIGN':([3,5,],[6,8,]),'LPAREN':([4,9,],[7,12,]),'KEYWORD_ENCRYPT':([6,],[9,]),'NUMBER':([8,],[11,]),'RPAREN':([10,15,],[13,17,]),'SEMI':([11,13,17,],[14,16,18,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'statement':([0,],[1,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('statement -> KEYWORD_SECRET ID ASSIGN NUMBER SEMI','statement',5,'p_statement_secret','parser.py',10),
  ('statement -> ID ASSIGN KEYWORD_ENCRYPT LPAREN ID RPAREN SEMI','statement',7,'p_statement_encrypt','parser.py',23),
  ('statement -> KEYWORD_SEND LPAREN ID RPAREN SEMI','statement',5,'p_statement_send','parser.py',36),
]
